# Generated by Django 5.2.11 on 2026-02-20 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('date_of_event', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(default='Barangay Central', max_length=255)),
                ('address', models.TextField(default='123 Main St, Barangay Central')),
                ('contact_info', models.CharField(default='0912-345-6789', max_length=255)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('receipt_header', models.TextField(default='OFFICIAL RECEIPT')),
                ('receipt_footer', models.TextField(default='Thank you for using our Gym Court!')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
