# Generated by Django 6.0.2 on 2026-02-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_cancellation_reason_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_type',
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
