# Generated by Django 6.0.2 on 2026-02-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_booking_event_type_alter_booking_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('SINGLE', 'Single Day'), ('MULTIPLE', 'Multiple Days')], default='SINGLE', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='parent_booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
