# Generated by Django 6.0.2 on 2026-02-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_booking_type_booking_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
    ]
