# Generated by Django 6.0.2 on 2026-03-29 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_booking_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='parent_booking_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='parent_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_bookings', to='core.booking'),
        ),
    ]
