# Generated by Django 6.0.2 on 2026-05-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_booking_parent_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='esp32_auth_token',
            field=models.CharField(default='brgy_gym_printer_2026', help_text='Authorization token used by the ESP32 endpoints', max_length=255),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='esp32_ip',
            field=models.GenericIPAddressField(blank=True, default='192.168.233.167', help_text='ESP32 printer bridge IP address', null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='esp32_port',
            field=models.PositiveIntegerField(default=80, help_text='ESP32 HTTP port'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='esp32_wifi_password',
            field=models.CharField(blank=True, help_text='Wi-Fi password for the ESP32 printer bridge', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='esp32_wifi_ssid',
            field=models.CharField(blank=True, help_text='Preferred 2.4GHz Wi-Fi SSID for the ESP32 printer bridge', max_length=255, null=True),
        ),
    ]
